name: Pull updated data

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Pull data from artifact api
        run: |
          ./pull.sh

      - name: commit and push
        run: |
          git remote rm origin
          git remote add origin ***github.com/noodlecontract/monkey-see.git
          git add --all
          git config user.name noodlecontract
          git config user.email noodlecontract@users.noreply.github.com
          git commit -m "pull new data"
          git push origin main
