name: Pull data

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Pull data from artifact api
        run: |
          ./pull.sh

      - name: commit and push
        run: |
          git add --all
          git config user.name noodlecontract
          git config user.email noodlecontract@users.noreply.github.com
          (git diff-index --quiet HEAD || git commit -m "pull new data") && git push
